---
- name: Create folder-test on the server
  hosts: pcbox-server-prod
  become: true
  gather_facts: false

  tasks:
    - name: Create /home/jhon/folder-test
      ansible.builtin.file:
        path: /home/jhon/folder-test
        state: directory
        mode: '0755'
        owner: jhon
        group: jhon
