---
- name: Crear carpeta en el servidor
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Eliminar /opt/hello
      ansible.builtin.file:
        path: /opt/hello
        state: absent
